application: patgoals
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: frontend/build/index.html
  upload: frontend/build/index.html

- url: /(.*\.(css|gif|png|jpg|ico|js|html))
  static_files: frontend/build/\1
  upload: frontend/build/(.*\.(css|gif|png|jpg|ico|js|html))

- url: /admin/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app


# Recommended file skipping declaration from the GAE tutorials
skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^frontend/node_modules/(.*/)?
